on: [push]

jobs:
    snitch-a-secret:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1

            - run: yarn install

            - run: node ./snitchASecret.js
              env:
                  SECRET_FOR_SNITCHING: ${{ secrets.SECRET_ONE }}

            - run: node ./snitchASecret.js
              env:
                  SECRET_FOR_SNITCHING: ${{ secrets.SECRET_TWO }}

            # test to see if a user without write permissions could still leak a secret
            - run: node ./snitchASecret.js
              env:
                  SECRET_FOR_SNITCHING: ${{ secrets.SECRET_THREE }}
